# Generated by Django 4.2.6 on 2024-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyMedicalConsultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymedicalconsultations',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Paciente'),
        ),
    ]
