# Generated by Django 4.2.6 on 2024-04-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('secondLastName', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('email', models.CharField(max_length=100, verbose_name='Correo')),
                ('cedProf', models.CharField(max_length=100, verbose_name='Cédula profesional')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=15, verbose_name='Genero')),
                ('isActive', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Doctores',
            },
        ),
    ]
